name: drama_flix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.11
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  freezed: ^3.2.0
  provider: ^6.1.5
  flutter_bloc: ^9.1.1

  flutter_localizations:
    sdk: flutter
  build_runner: ^2.7.0
  get_it: ^8.2.0
  firebase_core: ^4.0.0
  http: ^1.5.0
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  webview_flutter: ^4.13.0
  connectivity_plus: ^6.1.5
  flutter_facebook_auth: ^7.1.2
  firebase_auth: ^6.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_sign_in: ^7.1.1
  equatable: ^2.0.7
  json_serializable: ^6.10.0
  json_annotation: ^4.9.0
  carousel_slider: ^5.1.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/language/

